# Generated by Django 2.1.7 on 2019-02-23 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ansigger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='stream',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
