# Generated by Django 2.1.7 on 2019-03-31 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ansigger", "0002_auto_20190223_1551")]

    operations = [migrations.RenameModel(old_name="Log", new_name="Output")]
