#!/usr/bin/env ansible-playbook

- name: minimal ansible hello world
  hosts: localhost
  connection: local
#  gather_facts: false

  tasks:
    - name: "Show the hello world message"
      debug:
       msg: "hello world"
